### ISSUE TITLE
PNA的白盒模型

### ISSUE THREAD

**Issue by yangzhifeio** [zhipeng-wei/PNA-PatchOut#2]
观看代码说白盒模型是vit_large_patch16_224, levit_256, cait_s24_224, tnt_s_patch16_224
论文中描述的是ViT-B/16, PiT-B,CaiT-S-24 and Visformer-S
有些不明白实验的白盒模型到底是哪几个？

**Comment by zhipeng-wei** [comment]
感谢指正，已更新ReadMe。白盒模型是论文里面提到的ViT-B/16, PiT-B,CaiT-S-24 and Visformer-S。

**Comment by yangzhifeio** [comment]
白盒vit_base_patch16_224和黑盒deit_base_distilled_patch16_224(DeiT-B)的代码好像有小的问题

**Comment by zhipeng-wei** [comment]
具体是什么问题呢？
模型读取过程利用的timm，可能timm版本迭代之后，模型的名字会发生一些改变。

**Comment by yangzhifeio** [comment]
白盒&nbsp; &nbsp; vit_base_patch16_224


&nbsp; "See the documentation of nn.Upsample for details.".format(mode))
Using L2
Traceback (most recent call last):
&nbsp; File "/home/takai/code/transformer/our_attacks.py", line 54, in <module&gt;
&nbsp; &nbsp; adv_inps, loss_info = attack_method(batch_x, batch_y)
&nbsp; File "/home/takai/code/transformer/our_method.py", line 87, in __call__
&nbsp; &nbsp; images = self.forward(*input, **kwargs)
&nbsp; File "/home/takai/code/transformer/our_method.py", line 276, in forward
&nbsp; &nbsp; cost1 = self.loss_flag * loss(outputs, labels).cuda()&nbsp; &nbsp;# 计算输outputs和label之间的损失
&nbsp; File "/home/takai/.conda/envs/transformer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/takai/.conda/envs/transformer/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 962, in forward
&nbsp; &nbsp; ignore_index=self.ignore_index, reduction=self.reduction)
&nbsp; File "/home/takai/.conda/envs/transformer/lib/python3.7/site-packages/torch/nn/functional.py", line 2470, in cross_entropy
&nbsp; &nbsp; return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
&nbsp; File "/home/takai/.conda/envs/transformer/lib/python3.7/site-packages/torch/nn/functional.py", line 1607, in log_softmax
&nbsp; &nbsp; ret = input.log_softmax(dim)&nbsp; # zyf modify
AttributeError: 'list' object has no attribute 'log_softmax'


Process finished with exit code 1



这里input返回了列表类型&nbsp; &nbsp;input[0]才是一个Tensor类型






黑盒deit_base_distilled_patch16_224&nbsp; 在评估的时候，也出现了列表类型的情况


Using&nbsp; 1000
1000
Loading Model.
Ruing batch_idx 0
Traceback (most recent call last):
&nbsp; File "/home/takai/code/transformer/evaluate.py", line 56, in <module&gt;
&nbsp; &nbsp; acc1, acc5 = accuracy(output.detach(), batch_y, topk=(1, 5))&nbsp; # yzf 20220427 modify
AttributeError: 'list' object has no attribute 'detach'





our_attack.py



请多指教
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhipeng-wei/PNA-PatchOut"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月27日(星期三) 晚上9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhipeng-wei/PNA-PatchOut] PNA的白盒模型 (Issue #2)





 
具体是什么问题呢？
 模型读取过程利用的timm，可能timm版本迭代之后，模型的名字会发生一些改变。

**Comment by zhipeng-wei** [comment]
关于deit_base_distilled_patch16_224-评估：

- 模型的输出为list，所以导致output.detach()失败；
关于vit_base_patch16_224：

- loss(outputs, labels)，这里的outputs和labels其中存在list。需要你确定一下是outputs还是labels为list。如果是outputs的话，很可能也是因为模型的输出为list。

以上，猜测可能是timm版本的问题，修改了模型的输出。
你的timm是什么版本呢？这里是timm==0.4.13。
此外，如果还是解决不了，可以查看一下模型输出list分别是什么，找到logit值来计算loss或者评估。
希望可以解决你的问题😊

**Comment by yangzhifeio** [comment]
谢谢，不过我发现现在好像没有0.4.13版本的timm了，我使用的是0.4.12的版本

**Comment by zhipeng-wei** [comment]
如果还有问题，欢迎随时问哈

**Comment by yangzhifeio** [comment]
复现vit_base_patch16_224模型为白盒时，TOP-1达到99.3%&nbsp;&nbsp;

生成的图像会有这种鱼鳞状&nbsp; 不知道是什么原因


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhipeng-wei/PNA-PatchOut"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhipeng-wei/PNA-PatchOut] PNA的白盒模型 (Issue #2)





 
Closed #2.

**Comment by zhipeng-wei** [comment]
看不到你发的图片，生成的对抗图片会限制在||x_adv-x_clean||_∞<16，其他论文的方法也满足这样的限制下。
可以放大一下论文中的figure3，也是可以看到噪声的。

**Comment by yangzhifeio** [comment]
噪声可以看到，但是就是vit_base_patch16_224模型为白盒时，攻击其他模型的TOP-1很高，达到90+%，攻击效果不好，但是生成的图片是可以看到噪声的。
我在以其他模型为白盒时，就可以达到论文描述的准确率。我怕我是复现过程哪个地方出现了问题，但是一直没有找到，因为都是直接用源代码运行的。
请多指教


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhipeng-wei/PNA-PatchOut"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 晚上7:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhipeng-wei/PNA-PatchOut] PNA的白盒模型 (Issue #2)





 
看不到你发的图片，生成的对抗图片会限制在||x_adv-x_clean||_∞<16，其他论文的方法也满足这样的限制下。
 可以放大一下论文中的figure3，也是可以看到噪声的。

**Comment by zhipeng-wei** [comment]
是有点奇怪，猜测当前你使用版本的vit_base模型，在当前代码下（https://github.com/zhipeng-wei/PNA-PatchOut/blob/d2ca82e32926db94d065dbdd38cdd751f21c3c87/our_method.py#L117），执行register_backward_hook失败。
你可以输出当前版本下的vit_base模型，是否与该代码一致。

**Comment by yangzhifeio** [comment]
您能把您的vit_base模型发我一下吗？
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhipeng-wei/PNA-PatchOut"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhipeng-wei/PNA-PatchOut] PNA的白盒模型 (Issue #2)





 
是有点奇怪，猜测当前你使用版本的vit_base模型，在当前代码下（https://github.com/zhipeng-wei/PNA-PatchOut/blob/d2ca82e32926db94d065dbdd38cdd751f21c3c87/our_method.py#L117），执行register_backward_hook失败。
 你可以输出当前版本下的vit_base模型，是否与该代码一致。

**Comment by zhipeng-wei** [comment]
论文中使用的就是timm提供的‘vit_base_patch16_224’模型，没有进行过修改或者重新训练。
建议还是检查一下当前模型是否register_backward_hook成功。

**Comment by yangzhifeio** [comment]
你好，我想请问一下第二个实验是怎么做的呀？关于CNN的实验，接口需要改哪个地方呀？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhipeng-wei/PNA-PatchOut"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhipeng-wei/PNA-PatchOut] PNA的白盒模型 (Issue #2)





 
论文中使用的就是timm提供的‘vit_base_patch16_224’模型，没有进行过修改或者重新训练。
 建议还是检查一下当前模型是否register_backward_hook成功。

**Comment by zhipeng-wei** [comment]
第二个实验的对抗样本仍是由4个ViTs模型生成的，但是在CNNs上进行了评估。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, May 5, 2022 12:58 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; "State ***@***.***&gt;; 
Subject: &nbsp;Re: [zhipeng-wei/PNA-PatchOut] PNA的白盒模型 (Issue #2)

&nbsp;



 你好，我想请问一下第二个实验是怎么做的呀？关于CNN的实验，接口需要改哪个地方呀？ 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "zhipeng-wei/PNA-PatchOut"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年4月28日(星期四) 晚上9:05 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [zhipeng-wei/PNA-PatchOut] PNA的白盒模型 (Issue #2) 
 
 
 
 
 
   
 论文中使用的就是timm提供的‘vit_base_patch16_224’模型，没有进行过修改或者重新训练。 
  建议还是检查一下当前模型是否register_backward_hook成功。

**Comment by yangzhifeio** [comment]
您好&nbsp; &nbsp;您那有4个白盒模型分别攻击黑盒模型的成功率的数据吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhipeng-wei/PNA-PatchOut"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月6日(星期五) 下午3:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhipeng-wei/PNA-PatchOut] PNA的白盒模型 (Issue #2)





 第二个实验的对抗样本仍是由4个ViTs模型生成的，但是在CNNs上进行了评估。 
 &amp;nbsp; 
 &amp;nbsp; 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From: ***@***.***&amp;gt;; 
 Date: &amp;nbsp;Thu, May 5, 2022 12:58 PM 
 To: ***@***.***&amp;gt;;  
 Cc: ***@***.***&amp;gt;; "State ***@***.***&amp;gt;;  
 Subject: &amp;nbsp;Re: [zhipeng-wei/PNA-PatchOut] PNA的白盒模型 (Issue #2) 
 
 &amp;nbsp; 
 
 
 
  你好，我想请问一下第二个实验是怎么做的呀？关于CNN的实验，接口需要改哪个地方呀？  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "zhipeng-wei/PNA-PatchOut"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年4月28日(星期四) 晚上9:05  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [zhipeng-wei/PNA-PatchOut] PNA的白盒模型 (Issue #2)  
   
   
   
   
   
     
  论文中使用的就是timm提供的‘vit_base_patch16_224’模型，没有进行过修改或者重新训练。  
   建议还是检查一下当前模型是否register_backward_hook成功。

**Comment by yangzhifeio** [comment]
您那边方便把jx_vit_base_p16_224-4ee7a4dc.pth模型发我一下吗？附件的形式  谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhipeng-wei/PNA-PatchOut"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhipeng-wei/PNA-PatchOut] PNA的白盒模型 (Issue #2)





 
论文中使用的就是timm提供的‘vit_base_patch16_224’模型，没有进行过修改或者重新训练。
 建议还是检查一下当前模型是否register_backward_hook成功。

**Comment by yangzhifeio** [comment]
VanillaVisionTransformer(
&nbsp; (patch_embed): PatchEmbed(
&nbsp; &nbsp; (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
&nbsp; &nbsp; (norm): Identity()
&nbsp; )
&nbsp; (pos_drop): Dropout(p=0.0, inplace=False)
&nbsp; (blocks): Sequential(
&nbsp; &nbsp; (0): Block(
&nbsp; &nbsp; &nbsp; (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (attn): Attention(
&nbsp; &nbsp; &nbsp; &nbsp; (qkv): Linear(in_features=768, out_features=2304, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (attn_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; &nbsp; (proj): Linear(in_features=768, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (proj_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; (drop_path): Identity()
&nbsp; &nbsp; &nbsp; (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (mlp): Mlp(
&nbsp; &nbsp; &nbsp; &nbsp; (fc1): Linear(in_features=768, out_features=3072, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (act): GELU()
&nbsp; &nbsp; &nbsp; &nbsp; (fc2): Linear(in_features=3072, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (1): Block(
&nbsp; &nbsp; &nbsp; (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (attn): Attention(
&nbsp; &nbsp; &nbsp; &nbsp; (qkv): Linear(in_features=768, out_features=2304, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (attn_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; &nbsp; (proj): Linear(in_features=768, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (proj_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; (drop_path): Identity()
&nbsp; &nbsp; &nbsp; (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (mlp): Mlp(
&nbsp; &nbsp; &nbsp; &nbsp; (fc1): Linear(in_features=768, out_features=3072, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (act): GELU()
&nbsp; &nbsp; &nbsp; &nbsp; (fc2): Linear(in_features=3072, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (2): Block(
&nbsp; &nbsp; &nbsp; (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (attn): Attention(
&nbsp; &nbsp; &nbsp; &nbsp; (qkv): Linear(in_features=768, out_features=2304, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (attn_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; &nbsp; (proj): Linear(in_features=768, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (proj_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; (drop_path): Identity()
&nbsp; &nbsp; &nbsp; (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (mlp): Mlp(
&nbsp; &nbsp; &nbsp; &nbsp; (fc1): Linear(in_features=768, out_features=3072, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (act): GELU()
&nbsp; &nbsp; &nbsp; &nbsp; (fc2): Linear(in_features=3072, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (3): Block(
&nbsp; &nbsp; &nbsp; (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (attn): Attention(
&nbsp; &nbsp; &nbsp; &nbsp; (qkv): Linear(in_features=768, out_features=2304, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (attn_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; &nbsp; (proj): Linear(in_features=768, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (proj_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; (drop_path): Identity()
&nbsp; &nbsp; &nbsp; (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (mlp): Mlp(
&nbsp; &nbsp; &nbsp; &nbsp; (fc1): Linear(in_features=768, out_features=3072, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (act): GELU()
&nbsp; &nbsp; &nbsp; &nbsp; (fc2): Linear(in_features=3072, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (4): Block(
&nbsp; &nbsp; &nbsp; (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (attn): Attention(
&nbsp; &nbsp; &nbsp; &nbsp; (qkv): Linear(in_features=768, out_features=2304, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (attn_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; &nbsp; (proj): Linear(in_features=768, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (proj_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; (drop_path): Identity()
&nbsp; &nbsp; &nbsp; (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (mlp): Mlp(
&nbsp; &nbsp; &nbsp; &nbsp; (fc1): Linear(in_features=768, out_features=3072, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (act): GELU()
&nbsp; &nbsp; &nbsp; &nbsp; (fc2): Linear(in_features=3072, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (5): Block(
&nbsp; &nbsp; &nbsp; (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (attn): Attention(
&nbsp; &nbsp; &nbsp; &nbsp; (qkv): Linear(in_features=768, out_features=2304, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (attn_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; &nbsp; (proj): Linear(in_features=768, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (proj_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; (drop_path): Identity()
&nbsp; &nbsp; &nbsp; (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (mlp): Mlp(
&nbsp; &nbsp; &nbsp; &nbsp; (fc1): Linear(in_features=768, out_features=3072, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (act): GELU()
&nbsp; &nbsp; &nbsp; &nbsp; (fc2): Linear(in_features=3072, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (6): Block(
&nbsp; &nbsp; &nbsp; (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (attn): Attention(
&nbsp; &nbsp; &nbsp; &nbsp; (qkv): Linear(in_features=768, out_features=2304, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (attn_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; &nbsp; (proj): Linear(in_features=768, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (proj_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; (drop_path): Identity()
&nbsp; &nbsp; &nbsp; (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (mlp): Mlp(
&nbsp; &nbsp; &nbsp; &nbsp; (fc1): Linear(in_features=768, out_features=3072, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (act): GELU()
&nbsp; &nbsp; &nbsp; &nbsp; (fc2): Linear(in_features=3072, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (7): Block(
&nbsp; &nbsp; &nbsp; (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (attn): Attention(
&nbsp; &nbsp; &nbsp; &nbsp; (qkv): Linear(in_features=768, out_features=2304, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (attn_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; &nbsp; (proj): Linear(in_features=768, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (proj_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; (drop_path): Identity()
&nbsp; &nbsp; &nbsp; (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (mlp): Mlp(
&nbsp; &nbsp; &nbsp; &nbsp; (fc1): Linear(in_features=768, out_features=3072, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (act): GELU()
&nbsp; &nbsp; &nbsp; &nbsp; (fc2): Linear(in_features=3072, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (8): Block(
&nbsp; &nbsp; &nbsp; (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (attn): Attention(
&nbsp; &nbsp; &nbsp; &nbsp; (qkv): Linear(in_features=768, out_features=2304, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (attn_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; &nbsp; (proj): Linear(in_features=768, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (proj_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; (drop_path): Identity()
&nbsp; &nbsp; &nbsp; (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (mlp): Mlp(
&nbsp; &nbsp; &nbsp; &nbsp; (fc1): Linear(in_features=768, out_features=3072, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (act): GELU()
&nbsp; &nbsp; &nbsp; &nbsp; (fc2): Linear(in_features=3072, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (9): Block(
&nbsp; &nbsp; &nbsp; (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (attn): Attention(
&nbsp; &nbsp; &nbsp; &nbsp; (qkv): Linear(in_features=768, out_features=2304, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (attn_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; &nbsp; (proj): Linear(in_features=768, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (proj_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; (drop_path): Identity()
&nbsp; &nbsp; &nbsp; (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (mlp): Mlp(
&nbsp; &nbsp; &nbsp; &nbsp; (fc1): Linear(in_features=768, out_features=3072, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (act): GELU()
&nbsp; &nbsp; &nbsp; &nbsp; (fc2): Linear(in_features=3072, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (10): Block(
&nbsp; &nbsp; &nbsp; (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (attn): Attention(
&nbsp; &nbsp; &nbsp; &nbsp; (qkv): Linear(in_features=768, out_features=2304, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (attn_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; &nbsp; (proj): Linear(in_features=768, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (proj_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; (drop_path): Identity()
&nbsp; &nbsp; &nbsp; (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (mlp): Mlp(
&nbsp; &nbsp; &nbsp; &nbsp; (fc1): Linear(in_features=768, out_features=3072, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (act): GELU()
&nbsp; &nbsp; &nbsp; &nbsp; (fc2): Linear(in_features=3072, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; &nbsp; (11): Block(
&nbsp; &nbsp; &nbsp; (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (attn): Attention(
&nbsp; &nbsp; &nbsp; &nbsp; (qkv): Linear(in_features=768, out_features=2304, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (attn_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; &nbsp; (proj): Linear(in_features=768, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (proj_drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; &nbsp; (drop_path): Identity()
&nbsp; &nbsp; &nbsp; (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; &nbsp; &nbsp; (mlp): Mlp(
&nbsp; &nbsp; &nbsp; &nbsp; (fc1): Linear(in_features=768, out_features=3072, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (act): GELU()
&nbsp; &nbsp; &nbsp; &nbsp; (fc2): Linear(in_features=3072, out_features=768, bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; (drop): Dropout(p=0.0, inplace=False)
&nbsp; &nbsp; &nbsp; )
&nbsp; &nbsp; )
&nbsp; )
&nbsp; (norm): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
&nbsp; (pre_logits): Identity()
&nbsp; (head): Linear(in_features=768, out_features=1000, bias=True)
)



模型注册成功的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhipeng-wei/PNA-PatchOut"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhipeng-wei/PNA-PatchOut] PNA的白盒模型 (Issue #2)





 
论文中使用的就是timm提供的‘vit_base_patch16_224’模型，没有进行过修改或者重新训练。
 建议还是检查一下当前模型是否register_backward_hook成功。
